#!/bin/sh
#export CMAKE_CUDA_COMPILER=/opt/cuda/bin/nvcc
export CUDA_NVCC_EXECUTABLE=/usr/local/sbin/cuda/nvcc
export USE_CUDNN=1
export USE_ROCM=0
export TORCH_CUDA_ARCH_LIST=8.0
export OVERRIDE_TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"
export CUDNN_LIB_DIR=/usr/lib
export CUDNN_INCLUDE_DIR=/usr/include
export CC=/usr/local/sbin/gcc-12
export CXX=/usr/local/sbin/g++-12
export CUDAHOSTCXX=/opt/cuda/bin/g++
export CUDA_HOST_COMPILER=/opt/cuda/bin/g++
#export CUDA_VISIBLE_DEVICES=""
export CUDA_HOME=/opt/cuda
#export TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
export CXXFLAGS="${CXXFLAGS} -I third_party/ideep/mkl-dnn/third_party/oneDNN/include/"
export USE_SYSTEM_NCCL=ON
export USE_OPENCV=OFF
export USE_MKLDNN=ON
#export ATEN_NO_TEST=ON
export USE_GLOG=OFF
export VERBOSE=1
export ATEN_NO_TEST=OFF
export USE_MPI=OFF
export DEBUG=1
export USE_DISTRIBUTED=0
export USE_FFMPEG=1
export USE_CUDA=1
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/cuda/bin

